# Generated by Django 4.0.3 on 2022-06-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCat', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nomCat', models.CharField(max_length=30, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComent', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Comentario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre comentario')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido comentario')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo comentario')),
                ('nota', models.IntegerField(verbose_name='Nota comentario')),
                ('cometario', models.CharField(max_length=500, null=True, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCom', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Compra')),
                ('fechaCom', models.DateField(verbose_name='Fecha Compra')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPed', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idPro', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombrePro', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('precioPro', models.IntegerField(verbose_name='Precio Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsu', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Usuario')),
                ('nombreUsu', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
                ('emailUsu', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
    ]
