# Generated by Django 4.0.3 on 2022-06-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsu', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Usuario')),
                ('nombreUsu', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
            ],
        ),
    ]
