# Generated by Django 4.0.5 on 2022-06-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullTerrierWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='nota',
        ),
        migrations.AddField(
            model_name='comentario',
            name='calificacion',
            field=models.IntegerField(default='0', verbose_name='Calificación'),
        ),
    ]
