# Generated by Django 4.0.5 on 2022-06-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCat', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nomCat', models.CharField(max_length=30, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComent', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo electronico')),
                ('nota', models.IntegerField(verbose_name='Nota')),
                ('cometario', models.CharField(max_length=500, null=True, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsu', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Usuario')),
                ('nombreUsu', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
                ('emailUsu', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idPro', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombrePro', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('precioPro', models.IntegerField(verbose_name='Precio Producto')),
                ('idCat', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='BullTerrierWeb.categoria', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPed', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Pedido')),
                ('descPed', models.CharField(default='', max_length=1000, verbose_name='Descripción pedido')),
                ('idPro', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='BullTerrierWeb.producto', verbose_name='Id Producto')),
                ('idUsu', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='BullTerrierWeb.usuario', verbose_name='Id Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCom', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Compra')),
                ('fechaCom', models.DateField(verbose_name='Fecha Compra')),
                ('descCom', models.CharField(default='', max_length=1000, verbose_name='Descripción compra')),
                ('idPro', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='BullTerrierWeb.producto', verbose_name='Id Producto')),
                ('idUsu', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='BullTerrierWeb.usuario', verbose_name='Id Usuario')),
            ],
        ),
    ]
