# Generated by Django 4.0.5 on 2022-06-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullTerrierWeb', '0003_rename_cometario_comentario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='idComent',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
