# Generated by Django 4.0.5 on 2022-06-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullTerrierWeb', '0004_alter_comentario_idcoment'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripPro',
            field=models.CharField(default='', max_length=500, verbose_name='Descripción'),
        ),
    ]
