# Generated by Django 4.0.5 on 2022-06-09 07:30

import BullTerrierWeb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullTerrierWeb', '0005_producto_descrippro'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imgPro',
            field=models.ImageField(blank=True, null=True, upload_to=BullTerrierWeb.models.filepath),
        ),
    ]
