# Generated by Django 4.0.5 on 2022-06-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullTerrierWeb', '0006_producto_imgpro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imgPro',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
