# Generated by Django 4.0.5 on 2022-07-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullTerrierWeb', '0007_alter_producto_imgpro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imgPro',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen'),
        ),
    ]
