# Generated by Django 4.0.5 on 2022-07-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BullTerrierWeb', '0008_alter_producto_imgpro'),
        ('BullTerrierWeb', '0008_suscripcion_alter_producto_imgpro'),
    ]

    operations = [
    ]
