# Generated by Django 4.0.5 on 2022-07-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullTerrierWeb', '0009_merge_20220706_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='suscrito',
            field=models.BooleanField(default='True'),
        ),
    ]
