# Generated by Django 4.0.5 on 2022-07-08 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BullTerrierWeb', '0010_alter_suscripcion_suscrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarrito', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('Cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('Usuario', models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario')),
                ('idPro', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='BullTerrierWeb.producto', verbose_name='Id Producto')),
            ],
        ),
    ]
