# Generated by Django 4.0.5 on 2022-07-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullTerrierWeb', '0011_carrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='Cantidad',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='Usuario',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidadPro',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
