# Generated by Django 4.0.5 on 2022-07-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullTerrierWeb', '0012_rename_cantidad_carrito_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mostrarPro',
            field=models.BooleanField(default='True'),
        ),
    ]
