# Generated by Django 4.0.5 on 2022-07-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullTerrierWeb', '0013_producto_mostrarpro'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='donacion',
            field=models.IntegerField(default=0, verbose_name='Donación'),
        ),
    ]
