# Generated by Django 4.0.5 on 2022-07-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullTerrierWeb', '0014_suscripcion_donacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.IntegerField(default=0, verbose_name='Nombre de Usuario'),
        ),
    ]
